name: .NET Core CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0 # Replace with your .NET Core version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test

    - name: Publish
      run: dotnet publish -c Release -o ${{ github.workspace }}/publish

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: webapi-artifacts
        path: ${{ github.workspace }}/publish

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2

  #   - name: Download artifacts
  #     uses: actions/download-artifact@v2
  #     with:
  #       name: webapi-artifacts

  #   - name: Deploy to server or cloud (e.g., Azure, AWS, etc.)
  #     run: |
  #       # Add your deployment script here
  #       # Example: Use Azure Web App deployment
  #       az webapp deployment source config-zip --resource-group <resource-group> --name <app-name> --src ${{ github.workspace }}/publish/webapi.zip
